gps_api_administration:
    resource: "@GpsApiAdministrationBundle/Resources/config/routing.yml"
    prefix:   /

gps_api_espace_user:
    resource: "@GpsApiEspaceUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
# app/config/routing.yml
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

#def
def:
    resource: "@GpsApiAdministrationBundle/Controller/DefaultController.php"
    prefix:   /
    type:     rest
